### ISSUE TITLE
Bug while Running the RPP programs

### ISSUE THREAD

**Issue by pravee42** [aadhithya/rajiniPP#32]
# Bug Report
### Checklist
- [x] I am running the latest version of rajinipp.
- [x] I have searched the issues(open / closed) for this issue.
- [x] I have checked the project wiki.
- [x] This problem is reproducible.
- [x] This is not a feature request.

### Current Behaviour
```
(rajini) C:\Users\ABIPRAVI\rajini>rajinipp version
Traceback (most recent call last):
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\ABIPRAVI\Envs\rajini\Scripts\rajinipp.exe\__main__.py", line 4, in <module>
  File "C:\Users\ABIPRAVI\Envs\rajini\lib\site-packages\rajinipp\__init__.py", line 2, in <module>
    from . import ast, lexer, parser, runner, utils
  File "C:\Users\ABIPRAVI\Envs\rajini\lib\site-packages\rajinipp\runner.py", line 16, in <module>
    from .utils import read_yml
  File "C:\Users\ABIPRAVI\Envs\rajini\lib\site-packages\rajinipp\utils.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

### Expected Behaviour
`Version data`

### Steps to Reproduce
1. Make sure to install the `PyYAML` automatically in the requirements

```sh
pip install PyYAML
```

### Stack Trace / Screenshot
![image](https://github.com/aadhithya/rajiniPP/assets/65100038/92a04a68-a3b0-4f8c-ae05-79d30cf1af7d)

### General Info
* **rajinipp version**:latest
* **python version**:10
* **os platform**:Windows

**Comment by The-Robin-Hood** [comment]
Instead of `pip install PyYAML`  you have entered `pip install yaml` 
Have you installed the right version ??

**Comment by pravee42** [comment]
@The-Robin-Hood But it should be added in the dependencies right? while installing the application itself
